### ISSUE TITLE
could BoundTileLayer be declared outside of the function ? 

### ISSUE THREAD

**Issue by 12rambau** [banesullivan/localtileserver#104]
In one of my application, I'm scrolling in the layers displayed on my map and performed different operations depeding on where there from. The only way I can make the differents between something comming from localtileserver and another TileLayer is the type. In https://github.com/banesullivan/localtileserver/blob/165de5dc63b45689a72e22035f1fa2135eb93b71/localtileserver/widgets.py#L100 you are using the BoundTileLayer for your layer. it's quite hoard to reach for a simple `isinstance` test. would it be possible to set it as a standalone class in `localtileserver.widget` ?

**Comment by banesullivan** [comment]
@12rambau, would #105 work for you?

The feature in `BoundTileLayer` has actually been implemented in `ipyleaflet` so I planned on removing that class after most users upgraded to the latest version. It was internal so that I could easily remove it and let `ipyleaflet` handle the bounds. 

After some thought on what you described above, I think it would be useful to have a `localtileserver` mixin class for the `ipyleaflet` and `folium` tile layers generated here. #105 implements that mixin and it could provide an easy way to use `isinstance` to differentiate these layers.
