### ISSUE TITLE
Improve support for online COG 

### ISSUE THREAD

**Issue by giswqs** [banesullivan/localtileserver#21]
Based on the [example datasets](https://github.com/banesullivan/localtileserver/tree/main/localtileserver/data), it seems an XML file is needed to render COG hosted online. Any guidelines on how you created the XML file? It would be awesome if a tile client can be created the same way for both local and online COG files. 

Ideally, something like this:

```python
url = 'https://opendata.digitalglobe.com/events/california-fire-2020/pre-event/2018-02-16/pine-gulch-fire20/1030010076004E00.tif' 
tile_client = TileClient(url)
```
I used to rely on [titiler](https://github.com/developmentseed/titiler) to render online COGs. I am considering switching to localtileserver to support both local and online COGs. 

https://leafmap.org/notebooks/03_cog_stac/

```python
import leafmap
m = leafmap.Map()
url = 'https://opendata.digitalglobe.com/events/california-fire-2020/pre-event/2018-02-16/pine-gulch-fire20/1030010076004E00.tif'
m.add_cog_layer(url)
m
```

**Comment by banesullivan** [comment]
Aha, so you're bringing up something that I wanted to make clear with the name. `localtileserver` is intended to be used only serve tiles form raster files that exist on your filesystem. If you want a tile server that can handle accessing remote files, you have a few options:

1. We create a new `remotetileserver` package or submodule here 
2. You can use [Resonant GeoData](https://github.com/ResonantGeoData/ResonantGeoData) (which my team and I at Kitware have put a *TON* of work into handling tile serving from cloud-hosted data). See https://github.com/ResonantGeoData/ResonantGeoData/pull/603 for a demonstration.
3. You can use GDAL's Virtual Storage Interface since we're using `large_image` which is simply wrapping GDAL for data access.

In your particular case, this should work because your raster is a pre-tiled Cloud Optimized GeoTiff. I have this working locally with minimal changes to `localtileserver` I will push the change to a PR for you to test soon

**Comment by giswqs** [comment]
Resonant GeoData seems awesome. I need to look into it. It would be great if you can make localtileserver work for pre-tiled COG. It might be too much work to create and maintain another package like `remotetileserver`.

**Comment by banesullivan** [comment]
> It might be too much work to create and maintain another package like remotetileserver.

Well that is what Resonant GeoData is.... 😉
