### ISSUE TITLE
Bokeh tile server

### ISSUE THREAD

**Issue by avanetten** [banesullivan/localtileserver#89]
I'd like to use localtileserver in conjunction with [bokeh](https://docs.bokeh.org/en/latest/docs/user_guide/geo.html), though I'm not having luck.  Ideally, I'd like to spin up a bokeh server, though I haven't had luck within jupyter either.  I suspect this is related to [66](https://github.com/banesullivan/localtileserver/issues/66), just not sure exactly how to point bokeh to the tiles served up by this repo.

**Comment by banesullivan** [comment]
Totally doable with the `WMTSTileSource` model from bokeh: https://docs.bokeh.org/en/latest/docs/reference/models/tiles.html#bokeh.models.WMTSTileSource

I just pushed this example to the documentation: https://localtileserver.banesullivan.com/user-guide/bokeh.html

```py
from bokeh.plotting import figure, show
from bokeh.io import output_notebook
from bokeh.tile_providers import CARTODBPOSITRON, get_provider
from bokeh.models import WMTSTileSource
from localtileserver import TileClient, examples

output_notebook()

client = examples.get_san_francisco()
raster_provider = WMTSTileSource(url=client.get_tile_url())
bounds = client.bounds(projection='EPSG:3857')

basemap = get_provider(CARTODBPOSITRON)
p = figure(x_range=(bounds[2], bounds[3]), y_range=(bounds[0], bounds[1]),
           x_axis_type="mercator", y_axis_type="mercator")
p.add_tile(basemap)
p.add_tile(raster_provider)
show(p)
```

![Screen Shot 2022-05-04 at 4 09 59 PM](https://user-images.githubusercontent.com/22067021/166833866-4125ad82-e999-4975-a91f-394bda832d25.png)

----

It is important that you realize `localtileserver` is a *dynamic* tile server in that it launches a literal server on the host machine serving tiles which your mapping client makes HTTP requests to in the WMTS standard (slippy map standard: `/zoom/x/y.png`).

This means that if you use the output HTML file from bokeh, it will not work without that server running locally.

If you want to spin up your own production server so that you have a persistent tileserver, check out: https://github.com/banesullivan/remotetileserver

Or if you know you are going to always be accessing this on the same machine, you can launch `localtileserver` from the command line on a specified port and use that port when instantiating your `TileClient`: ` python -m localtileserver -p 8080`

Otherwise, the script I shared above will work in Jupyter and JupyterHub cloud environments:

**Comment by giswqs** [comment]
Nice! Looks like I can add bokeh to leafmap as a new plotting backend.

**Comment by avanetten** [comment]
Amazing, thanks @banesullivan.

**Comment by banesullivan** [comment]
Reach out if you're still having trouble getting this running in a "remote" environment and perhaps le me know how I can improve this page: https://localtileserver.banesullivan.com/installation/remote-jupyter.html

In the meantime, I'm going to close this issue

**Comment by banesullivan** [comment]
@avanetten, great [blog post](https://medium.com/geodesic/serving-up-spacenet-imagery-for-bokeh-e85b8fffe05)!! I noticed that there we a few links to this repository: https://github.com/avanetten/spacenet-tiler which doesn't seem to exist. Is the code you are referencing in the bog open?

**Comment by banesullivan** [comment]
Also, thought I'd point out that the imagery from the SpaceNet collection are NOT actually Cloud Optimized GeoTiffs - they might as well be plain old GeoTiffs because they lack overviews. `localtileserver` handles COGs or non-COGs all the same, it's just that non-COGs, like this imagery, have very poor performance.

Thought I'd note this in case you or others are wondering why those images are so slow to render (even after downloading locally)

```py
from osgeo import gdal
gdal.SetConfigOption("AWS_NO_SIGN_REQUEST", "YES")

from localtileserver.validate import validate_cog

validate_cog('s3://spacenet-dataset/AOIs/AOI_10_Dar_Es_Salaam/PS-RGB/AOI_10_Dar_Es_Salaam_PS-RGB_COG.tif')
```
```
---------------------------------------------------------------------------
ValidateCloudOptimizedGeoTIFFException    Traceback (most recent call last)
Input In [5], in <cell line: 6>()
      2 gdal.SetConfigOption("AWS_NO_SIGN_REQUEST", "YES")
      4 from localtileserver.validate import validate_cog
----> 6 validate_cog('s3://spacenet-dataset/AOIs/AOI_10_Dar_Es_Salaam/PS-RGB/AOI_10_Dar_Es_Salaam_PS-RGB_COG.tif')

File ~/Software/banesullivan/localtileserver/localtileserver/validate.py:35, in validate_cog(path, check_tiled, full_check, strict, warn)
     33     raise ValidateCloudOptimizedGeoTIFFException(errors)
     34 if strict and warnings:
---> 35     raise ValidateCloudOptimizedGeoTIFFException(warnings)
     36 if warn:
     37     for warning in warnings:

ValidateCloudOptimizedGeoTIFFException: ['The file is greater than 512xH or Wx512, it is recommended to include internal overviews']
```

**Comment by banesullivan** [comment]
Aha, I think I found the repo here: https://github.com/Geodesic-Labs/bokeh-tiler

**Comment by avanetten** [comment]
@banesullivan Thanks for the feedback.  I did indeed have a few broken links (now fixed) in the blog post, and you are correct that the repo is at: [https://github.com/avanetten/bokeh-tiler](https://github.com/avanetten/bokeh-tiler).

I'd also never bothered to check if the purported COG was actually a COG, so thanks for that.  I've updated the README in bokeh-tiler to ensure that the tiled file is indeed a COG.
